[fix] Fix async issue with transformer
When passing an async function, you will get the error
`TypeError: transformer(...).map is not a function`
which is correct becuse Promise.map is not a function.
Adding the parentheses will execute the async transform,
and then apply `.map` to the arround returned

Addesses issue: https://github.com/algolia/gatsby-plugin-algolia/issues/73